# @package _global_
defaults:
  - base
  - _self_

agent_config:
  use_user_prompt: false
  use_repo_info: false
  use_unit_tests_info: false
  use_spec_info: false
  use_lint_info: true
  pre_commit_config_path: .pre-commit-config.yaml
  run_tests: false
