# @package _global_
defaults:
  - base
  - _self_

commit0_config:
  repo_split: minitorch

agent_config:
  use_user_prompt: false
  use_repo_info: false
  use_unit_tests_info: false
  use_reference_info: false
  use_lint_info: false
  pre_commit_config_path: .pre-commit-config.yaml
  run_tests: false
