name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Set up Python
        run: uv venv --python 3.12
      - name: Install the project
        run: uv sync --extra agent
      - name: Install the project
        run: uv pip install pre-commit
      - name: PreCommit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
